// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NoirSFUClient is the client API for NoirSFU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoirSFUClient interface {
	Admin(ctx context.Context, opts ...grpc.CallOption) (NoirSFU_AdminClient, error)
}

type noirSFUClient struct {
	cc grpc.ClientConnInterface
}

func NewNoirSFUClient(cc grpc.ClientConnInterface) NoirSFUClient {
	return &noirSFUClient{cc}
}

func (c *noirSFUClient) Admin(ctx context.Context, opts ...grpc.CallOption) (NoirSFU_AdminClient, error) {
	stream, err := c.cc.NewStream(ctx, &NoirSFU_ServiceDesc.Streams[0], "/noir.NoirSFU/Admin", opts...)
	if err != nil {
		return nil, err
	}
	x := &noirSFUAdminClient{stream}
	return x, nil
}

type NoirSFU_AdminClient interface {
	Send(*NoirRequest) error
	Recv() (*NoirReply, error)
	grpc.ClientStream
}

type noirSFUAdminClient struct {
	grpc.ClientStream
}

func (x *noirSFUAdminClient) Send(m *NoirRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *noirSFUAdminClient) Recv() (*NoirReply, error) {
	m := new(NoirReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NoirSFUServer is the server API for NoirSFU service.
// All implementations must embed UnimplementedNoirSFUServer
// for forward compatibility
type NoirSFUServer interface {
	Admin(NoirSFU_AdminServer) error
	mustEmbedUnimplementedNoirSFUServer()
}

// UnimplementedNoirSFUServer must be embedded to have forward compatible implementations.
type UnimplementedNoirSFUServer struct {
}

func (UnimplementedNoirSFUServer) Admin(NoirSFU_AdminServer) error {
	return status.Errorf(codes.Unimplemented, "method Admin not implemented")
}
func (UnimplementedNoirSFUServer) mustEmbedUnimplementedNoirSFUServer() {}

// UnsafeNoirSFUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoirSFUServer will
// result in compilation errors.
type UnsafeNoirSFUServer interface {
	mustEmbedUnimplementedNoirSFUServer()
}

func RegisterNoirSFUServer(s grpc.ServiceRegistrar, srv NoirSFUServer) {
	s.RegisterService(&NoirSFU_ServiceDesc, srv)
}

func _NoirSFU_Admin_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NoirSFUServer).Admin(&noirSFUAdminServer{stream})
}

type NoirSFU_AdminServer interface {
	Send(*NoirReply) error
	Recv() (*NoirRequest, error)
	grpc.ServerStream
}

type noirSFUAdminServer struct {
	grpc.ServerStream
}

func (x *noirSFUAdminServer) Send(m *NoirReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *noirSFUAdminServer) Recv() (*NoirRequest, error) {
	m := new(NoirRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NoirSFU_ServiceDesc is the grpc.ServiceDesc for NoirSFU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoirSFU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noir.NoirSFU",
	HandlerType: (*NoirSFUServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Admin",
			Handler:       _NoirSFU_Admin_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/noir.proto",
}
