// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: pkg/proto/status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoirStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Status:
	//	*NoirStatus_Worker
	//	*NoirStatus_Room
	//	*NoirStatus_Peer
	Status isNoirStatus_Status `protobuf_oneof:"status"`
}

func (x *NoirStatus) Reset() {
	*x = NoirStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoirStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoirStatus) ProtoMessage() {}

func (x *NoirStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoirStatus.ProtoReflect.Descriptor instead.
func (*NoirStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_status_proto_rawDescGZIP(), []int{0}
}

func (m *NoirStatus) GetStatus() isNoirStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *NoirStatus) GetWorker() *WorkerStatus {
	if x, ok := x.GetStatus().(*NoirStatus_Worker); ok {
		return x.Worker
	}
	return nil
}

func (x *NoirStatus) GetRoom() *RoomStatus {
	if x, ok := x.GetStatus().(*NoirStatus_Room); ok {
		return x.Room
	}
	return nil
}

func (x *NoirStatus) GetPeer() *PeerStatus {
	if x, ok := x.GetStatus().(*NoirStatus_Peer); ok {
		return x.Peer
	}
	return nil
}

type isNoirStatus_Status interface {
	isNoirStatus_Status()
}

type NoirStatus_Worker struct {
	Worker *WorkerStatus `protobuf:"bytes,1,opt,name=worker,proto3,oneof"`
}

type NoirStatus_Room struct {
	Room *RoomStatus `protobuf:"bytes,2,opt,name=room,proto3,oneof"`
}

type NoirStatus_Peer struct {
	Peer *PeerStatus `protobuf:"bytes,3,opt,name=peer,proto3,oneof"`
}

func (*NoirStatus_Worker) isNoirStatus_Status() {}

func (*NoirStatus_Room) isNoirStatus_Status() {}

func (*NoirStatus_Peer) isNoirStatus_Status() {}

type WorkerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdate string `protobuf:"bytes,2,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_status_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerStatus) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type RoomStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdate string `protobuf:"bytes,2,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Title      string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	WorkerID   string `protobuf:"bytes,4,opt,name=workerID,proto3" json:"workerID,omitempty"`
}

func (x *RoomStatus) Reset() {
	*x = RoomStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatus) ProtoMessage() {}

func (x *RoomStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatus.ProtoReflect.Descriptor instead.
func (*RoomStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_status_proto_rawDescGZIP(), []int{2}
}

func (x *RoomStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomStatus) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *RoomStatus) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomStatus) GetWorkerID() string {
	if x != nil {
		return x.WorkerID
	}
	return ""
}

type PeerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdate string `protobuf:"bytes,2,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	RoomID     string `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_status_proto_rawDescGZIP(), []int{3}
}

func (x *PeerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerStatus) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *PeerStatus) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

var File_pkg_proto_status_proto protoreflect.FileDescriptor

var file_pkg_proto_status_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6f, 0x69, 0x72, 0x22, 0x94,
	0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x69, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a,
	0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6e, 0x6f, 0x69, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x69, 0x72,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x69, 0x72, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x6e, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x44, 0x22, 0x54, 0x0a, 0x0a, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x42, 0x27, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x74, 0x2d, 0x70, 0x72,
	0x6f, 0x70, 0x68, 0x65, 0x74, 0x2f, 0x6e, 0x6f, 0x69, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_status_proto_rawDescOnce sync.Once
	file_pkg_proto_status_proto_rawDescData = file_pkg_proto_status_proto_rawDesc
)

func file_pkg_proto_status_proto_rawDescGZIP() []byte {
	file_pkg_proto_status_proto_rawDescOnce.Do(func() {
		file_pkg_proto_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_status_proto_rawDescData)
	})
	return file_pkg_proto_status_proto_rawDescData
}

var file_pkg_proto_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_status_proto_goTypes = []interface{}{
	(*NoirStatus)(nil),   // 0: noir.NoirStatus
	(*WorkerStatus)(nil), // 1: noir.WorkerStatus
	(*RoomStatus)(nil),   // 2: noir.RoomStatus
	(*PeerStatus)(nil),   // 3: noir.PeerStatus
}
var file_pkg_proto_status_proto_depIdxs = []int32{
	1, // 0: noir.NoirStatus.worker:type_name -> noir.WorkerStatus
	2, // 1: noir.NoirStatus.room:type_name -> noir.RoomStatus
	3, // 2: noir.NoirStatus.peer:type_name -> noir.PeerStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_status_proto_init() }
func file_pkg_proto_status_proto_init() {
	if File_pkg_proto_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoirStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_status_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NoirStatus_Worker)(nil),
		(*NoirStatus_Room)(nil),
		(*NoirStatus_Peer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_status_proto_goTypes,
		DependencyIndexes: file_pkg_proto_status_proto_depIdxs,
		MessageInfos:      file_pkg_proto_status_proto_msgTypes,
	}.Build()
	File_pkg_proto_status_proto = out.File
	file_pkg_proto_status_proto_rawDesc = nil
	file_pkg_proto_status_proto_goTypes = nil
	file_pkg_proto_status_proto_depIdxs = nil
}
